package GUI;

import Control.MapManager;
import java.awt.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;

public class MapUI extends javax.swing.JFrame 
{
    public MapManager mapm;
    public MapUI() 
    {
        initComponents();
        setSize(1200, 700);
        mapm = new MapManager();
        
        //Hover on Facility Effect
        AllFacilityMouseEntered();
        AllFacilityMouseExited();
        label11.setVisible(false);
        
        //View Facility names on map
        mapFacilityView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoDialog = new javax.swing.JDialog();
        facilityInfoLabel = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneNum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        workFrom = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        workTo = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        SupportDialog = new javax.swing.JDialog();
        inqLabel = new javax.swing.JLabel();
        InqPanel = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        inqTypeBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        inqDescription = new javax.swing.JTextPane();
        sendBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        callBtn = new javax.swing.JButton();
        SideBar = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchicon = new javax.swing.JLabel();
        supportPanel = new javax.swing.JPanel();
        calltext = new javax.swing.JLabel();
        callicon = new javax.swing.JLabel();
        MapLogo = new javax.swing.JLabel();
        MapLogo1 = new javax.swing.JLabel();
        MapLogo2 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        MapPanel = new javax.swing.JPanel();
        f18 = new javax.swing.JPanel();
        label18 = new javax.swing.JLabel();
        f17 = new javax.swing.JPanel();
        label17 = new javax.swing.JLabel();
        f16 = new javax.swing.JPanel();
        label16 = new javax.swing.JLabel();
        f15 = new javax.swing.JPanel();
        label15 = new javax.swing.JLabel();
        f14 = new javax.swing.JPanel();
        label14 = new javax.swing.JLabel();
        f13 = new javax.swing.JPanel();
        label13 = new javax.swing.JLabel();
        f12 = new javax.swing.JPanel();
        label12 = new javax.swing.JLabel();
        f11 = new javax.swing.JPanel();
        label11 = new javax.swing.JLabel();
        f10 = new javax.swing.JPanel();
        label10 = new javax.swing.JLabel();
        f9 = new javax.swing.JPanel();
        label9 = new javax.swing.JLabel();
        f8 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        f7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        f6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        f5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        f4 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        f3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        f2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        f1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        mapImg = new javax.swing.JLabel();
        RightBar = new javax.swing.JPanel();
        FacilityLabel = new javax.swing.JLabel();
        infoBtn = new javax.swing.JPanel();
        infoText = new javax.swing.JLabel();
        dirBtn = new javax.swing.JPanel();
        dirText = new javax.swing.JLabel();
        adPanel = new javax.swing.JPanel();
        adimg = new javax.swing.JLabel();

        InfoDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        InfoDialog.setTitle("Place Information");
        InfoDialog.setMinimumSize(new java.awt.Dimension(404, 351));
        InfoDialog.setResizable(false);
        InfoDialog.setSize(new java.awt.Dimension(404, 351));

        facilityInfoLabel.setBackground(new java.awt.Color(104, 134, 197));
        facilityInfoLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 32)); // NOI18N
        facilityInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        facilityInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facilityInfoLabel.setText("Facility");
        facilityInfoLabel.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Category: ");

        category.setBackground(new java.awt.Color(255, 255, 255));
        category.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        category.setText("text");
        category.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Phone Number: ");

        phoneNum.setBackground(new java.awt.Color(255, 255, 255));
        phoneNum.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        phoneNum.setText("text");
        phoneNum.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Description: ");

        description.setBackground(new java.awt.Color(255, 255, 255));
        description.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        description.setText("text");
        description.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        description.setAutoscrolls(true);
        description.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Opening: ");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("from: ");
        jLabel10.setOpaque(true);

        workFrom.setBackground(new java.awt.Color(255, 255, 255));
        workFrom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        workFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workFrom.setText("HH");
        workFrom.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("to: ");
        jLabel12.setOpaque(true);

        workTo.setBackground(new java.awt.Color(255, 255, 255));
        workTo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        workTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workTo.setText("HH");
        workTo.setOpaque(true);

        okBtn.setText("OK");
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workTo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(category))
                .addGap(18, 18, 18)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneNum))
                .addGap(18, 18, 18)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(workTo)
                    .addComponent(jLabel12)
                    .addComponent(workFrom))
                .addGap(18, 18, 18)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(okBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout InfoDialogLayout = new javax.swing.GroupLayout(InfoDialog.getContentPane());
        InfoDialog.getContentPane().setLayout(InfoDialogLayout);
        InfoDialogLayout.setHorizontalGroup(
            InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facilityInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InfoDialogLayout.setVerticalGroup(
            InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoDialogLayout.createSequentialGroup()
                .addComponent(facilityInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inqLabel.setBackground(new java.awt.Color(104, 134, 197));
        inqLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 32)); // NOI18N
        inqLabel.setForeground(new java.awt.Color(255, 255, 255));
        inqLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inqLabel.setText("Contact Customer Service");
        inqLabel.setOpaque(true);

        text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text1.setText("I want to send an Inquiry for :");

        inqTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Need Help", "Complain", "Suggest", "Other" }));

        inqDescription.setText("Write your Inquiry here");
        jScrollPane1.setViewportView(inqDescription);

        sendBtn.setText("Send");
        sendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtnMouseClicked(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        callBtn.setText("Call Us");
        callBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InqPanelLayout = new javax.swing.GroupLayout(InqPanel);
        InqPanel.setLayout(InqPanelLayout);
        InqPanelLayout.setHorizontalGroup(
            InqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InqPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(InqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InqPanelLayout.createSequentialGroup()
                        .addComponent(callBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(InqPanelLayout.createSequentialGroup()
                        .addGroup(InqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(InqPanelLayout.createSequentialGroup()
                                .addComponent(text1)
                                .addGap(18, 18, 18)
                                .addComponent(inqTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        InqPanelLayout.setVerticalGroup(
            InqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InqPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(InqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text1)
                    .addComponent(inqTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(InqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBtn)
                    .addComponent(cancelBtn)
                    .addComponent(callBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout SupportDialogLayout = new javax.swing.GroupLayout(SupportDialog.getContentPane());
        SupportDialog.getContentPane().setLayout(SupportDialogLayout);
        SupportDialogLayout.setHorizontalGroup(
            SupportDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InqPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SupportDialogLayout.setVerticalGroup(
            SupportDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportDialogLayout.createSequentialGroup()
                .addComponent(inqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InqPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Mall Map");
        setMinimumSize(new java.awt.Dimension(900, 525));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        SideBar.setBackground(new java.awt.Color(104, 134, 197));
        SideBar.setForeground(new java.awt.Color(255, 255, 255));
        SideBar.setMaximumSize(new java.awt.Dimension(120, 32767));
        SideBar.setMinimumSize(new java.awt.Dimension(80, 0));
        SideBar.setPreferredSize(new java.awt.Dimension(120, 700));

        searchPanel.setBackground(new java.awt.Color(104, 134, 197));
        searchPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchPanelMouseExited(evt);
            }
        });

        searchicon.setBackground(new java.awt.Color(153, 51, 255));
        searchicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search icon.png"))); // NOI18N

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchicon, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchicon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        supportPanel.setBackground(new java.awt.Color(104, 134, 197));
        supportPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supportPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supportPanelMouseExited(evt);
            }
        });

        calltext.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        calltext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calltext.setText("Call Support");

        callicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        callicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/headset icon.png"))); // NOI18N
        callicon.setToolTipText("");

        javax.swing.GroupLayout supportPanelLayout = new javax.swing.GroupLayout(supportPanel);
        supportPanel.setLayout(supportPanelLayout);
        supportPanelLayout.setHorizontalGroup(
            supportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calltext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(callicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        supportPanelLayout.setVerticalGroup(
            supportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supportPanelLayout.createSequentialGroup()
                .addComponent(callicon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calltext, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MapLogo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        MapLogo.setForeground(new java.awt.Color(255, 255, 255));
        MapLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MapLogo.setLabelFor(SideBar);
        MapLogo.setText("Smart");
        MapLogo.setToolTipText("");
        MapLogo.setMaximumSize(new java.awt.Dimension(100, 100));
        MapLogo.setMinimumSize(new java.awt.Dimension(100, 100));
        MapLogo.setPreferredSize(new java.awt.Dimension(100, 100));

        MapLogo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        MapLogo1.setForeground(new java.awt.Color(255, 255, 255));
        MapLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MapLogo1.setLabelFor(SideBar);
        MapLogo1.setText("Mall");
        MapLogo1.setToolTipText("");
        MapLogo1.setMaximumSize(new java.awt.Dimension(100, 100));
        MapLogo1.setMinimumSize(new java.awt.Dimension(100, 100));
        MapLogo1.setPreferredSize(new java.awt.Dimension(100, 100));

        MapLogo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        MapLogo2.setForeground(new java.awt.Color(255, 255, 255));
        MapLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MapLogo2.setLabelFor(SideBar);
        MapLogo2.setText("Map");
        MapLogo2.setToolTipText("");
        MapLogo2.setMaximumSize(new java.awt.Dimension(100, 100));
        MapLogo2.setMinimumSize(new java.awt.Dimension(100, 100));
        MapLogo2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MapLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MapLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MapLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(MapLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MapLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MapLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(supportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(SideBar);

        MainPanel.setBackground(new java.awt.Color(244, 244, 244));
        MainPanel.setMinimumSize(new java.awt.Dimension(160, 0));
        MainPanel.setPreferredSize(new java.awt.Dimension(780, 700));

        MapPanel.setBackground(new java.awt.Color(244, 244, 244));
        MapPanel.setLayout(null);

        f18.setBackground(new java.awt.Color(249, 227, 133));
        f18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f18MouseClicked(evt);
            }
        });

        label18.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("Facility");

        javax.swing.GroupLayout f18Layout = new javax.swing.GroupLayout(f18);
        f18.setLayout(f18Layout);
        f18Layout.setHorizontalGroup(
            f18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f18Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        f18Layout.setVerticalGroup(
            f18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f18Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(label18)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        MapPanel.add(f18);
        f18.setBounds(70, 150, 140, 130);

        f17.setBackground(new java.awt.Color(249, 227, 133));
        f17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f17MouseClicked(evt);
            }
        });

        label17.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label17.setText("Facility");

        javax.swing.GroupLayout f17Layout = new javax.swing.GroupLayout(f17);
        f17.setLayout(f17Layout);
        f17Layout.setHorizontalGroup(
            f17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label17, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        f17Layout.setVerticalGroup(
            f17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f17Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(label17)
                .addGap(52, 52, 52))
        );

        MapPanel.add(f17);
        f17.setBounds(220, 150, 80, 130);

        f16.setBackground(new java.awt.Color(249, 227, 133));
        f16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f16MouseClicked(evt);
            }
        });

        label16.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label16.setText("Facility");

        javax.swing.GroupLayout f16Layout = new javax.swing.GroupLayout(f16);
        f16.setLayout(f16Layout);
        f16Layout.setHorizontalGroup(
            f16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label16, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        f16Layout.setVerticalGroup(
            f16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f16Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(label16)
                .addGap(52, 52, 52))
        );

        MapPanel.add(f16);
        f16.setBounds(310, 150, 80, 130);

        f15.setBackground(new java.awt.Color(249, 227, 133));
        f15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f15MouseClicked(evt);
            }
        });

        label15.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label15.setText("Facility");

        javax.swing.GroupLayout f15Layout = new javax.swing.GroupLayout(f15);
        f15.setLayout(f15Layout);
        f15Layout.setHorizontalGroup(
            f15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f15Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        f15Layout.setVerticalGroup(
            f15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f15Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label15)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        MapPanel.add(f15);
        f15.setBounds(70, 40, 360, 100);

        f14.setBackground(new java.awt.Color(249, 227, 133));
        f14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f14MouseClicked(evt);
            }
        });

        label14.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label14.setText("Facility");

        javax.swing.GroupLayout f14Layout = new javax.swing.GroupLayout(f14);
        f14.setLayout(f14Layout);
        f14Layout.setHorizontalGroup(
            f14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label14, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        f14Layout.setVerticalGroup(
            f14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label14)
                .addGap(51, 51, 51))
        );

        MapPanel.add(f14);
        f14.setBounds(440, 40, 100, 50);

        f13.setBackground(new java.awt.Color(249, 227, 133));
        f13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f13MouseClicked(evt);
            }
        });

        label13.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label13.setText("Facility");

        javax.swing.GroupLayout f13Layout = new javax.swing.GroupLayout(f13);
        f13.setLayout(f13Layout);
        f13Layout.setHorizontalGroup(
            f13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label13, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        f13Layout.setVerticalGroup(
            f13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label13)
                .addGap(51, 51, 51))
        );

        MapPanel.add(f13);
        f13.setBounds(550, 40, 110, 50);

        f12.setBackground(new java.awt.Color(249, 227, 133));
        f12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f12.setOpaque(false);
        f12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f12MouseClicked(evt);
            }
        });

        label12.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("Facility");

        javax.swing.GroupLayout f12Layout = new javax.swing.GroupLayout(f12);
        f12.setLayout(f12Layout);
        f12Layout.setHorizontalGroup(
            f12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label12, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        f12Layout.setVerticalGroup(
            f12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f12Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(label12)
                .addGap(61, 61, 61))
        );

        MapPanel.add(f12);
        f12.setBounds(670, 40, 170, 240);

        f11.setBackground(new java.awt.Color(249, 227, 133));
        f11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f11.setOpaque(false);
        f11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f11MouseClicked(evt);
            }
        });

        label11.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("Facility");

        javax.swing.GroupLayout f11Layout = new javax.swing.GroupLayout(f11);
        f11.setLayout(f11Layout);
        f11Layout.setHorizontalGroup(
            f11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        f11Layout.setVerticalGroup(
            f11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        MapPanel.add(f11);
        f11.setBounds(720, 290, 120, 40);

        f10.setBackground(new java.awt.Color(249, 227, 133));
        f10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f10MouseClicked(evt);
            }
        });

        label10.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("Facility");

        javax.swing.GroupLayout f10Layout = new javax.swing.GroupLayout(f10);
        f10.setLayout(f10Layout);
        f10Layout.setHorizontalGroup(
            f10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        f10Layout.setVerticalGroup(
            f10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(f10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f10);
        f10.setBounds(580, 390, 80, 60);

        f9.setBackground(new java.awt.Color(249, 227, 133));
        f9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f9MouseClicked(evt);
            }
        });

        label9.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("Facility");

        javax.swing.GroupLayout f9Layout = new javax.swing.GroupLayout(f9);
        f9.setLayout(f9Layout);
        f9Layout.setHorizontalGroup(
            f9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(f9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f9Layout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        f9Layout.setVerticalGroup(
            f9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(f9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, f9Layout.createSequentialGroup()
                    .addContainerGap(45, Short.MAX_VALUE)
                    .addComponent(label9)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        MapPanel.add(f9);
        f9.setBounds(670, 340, 170, 110);

        f8.setBackground(new java.awt.Color(249, 227, 133));
        f8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f8MouseClicked(evt);
            }
        });

        label8.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("Facility");

        javax.swing.GroupLayout f8Layout = new javax.swing.GroupLayout(f8);
        f8.setLayout(f8Layout);
        f8Layout.setHorizontalGroup(
            f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f8Layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(label8)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );
        f8Layout.setVerticalGroup(
            f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f8);
        f8.setBounds(740, 460, 100, 80);

        f7.setBackground(new java.awt.Color(249, 227, 133));
        f7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f7MouseClicked(evt);
            }
        });

        label7.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("Facility");

        javax.swing.GroupLayout f7Layout = new javax.swing.GroupLayout(f7);
        f7.setLayout(f7Layout);
        f7Layout.setHorizontalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f7Layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(label7)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );
        f7Layout.setVerticalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f7);
        f7.setBounds(740, 550, 100, 80);

        f6.setBackground(new java.awt.Color(249, 227, 133));
        f6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f6MouseClicked(evt);
            }
        });

        label6.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("Facility");

        javax.swing.GroupLayout f6Layout = new javax.swing.GroupLayout(f6);
        f6.setLayout(f6Layout);
        f6Layout.setHorizontalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f6Layout.createSequentialGroup()
                    .addGap(0, 105, Short.MAX_VALUE)
                    .addComponent(label6)
                    .addGap(0, 105, Short.MAX_VALUE)))
        );
        f6Layout.setVerticalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f6);
        f6.setBounds(400, 530, 260, 100);

        f5.setBackground(new java.awt.Color(249, 227, 133));
        f5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f5MouseClicked(evt);
            }
        });

        label5.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("Facility");

        javax.swing.GroupLayout f5Layout = new javax.swing.GroupLayout(f5);
        f5.setLayout(f5Layout);
        f5Layout.setHorizontalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f5Layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(label5)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );
        f5Layout.setVerticalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f5);
        f5.setBounds(400, 390, 100, 120);

        f4.setBackground(new java.awt.Color(249, 227, 133));
        f4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f4MouseClicked(evt);
            }
        });

        label4.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Facility");

        javax.swing.GroupLayout f4Layout = new javax.swing.GroupLayout(f4);
        f4.setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f4);
        f4.setBounds(320, 390, 70, 80);

        f3.setBackground(new java.awt.Color(249, 227, 133));
        f3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3MouseClicked(evt);
            }
        });

        label3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Facility");

        javax.swing.GroupLayout f3Layout = new javax.swing.GroupLayout(f3);
        f3.setLayout(f3Layout);
        f3Layout.setHorizontalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        f3Layout.setVerticalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f3);
        f3.setBounds(260, 390, 51, 80);

        f2.setBackground(new java.awt.Color(249, 227, 133));
        f2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2MouseClicked(evt);
            }
        });

        label2.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Facility");

        javax.swing.GroupLayout f2Layout = new javax.swing.GroupLayout(f2);
        f2.setLayout(f2Layout);
        f2Layout.setHorizontalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        f2Layout.setVerticalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f2);
        f2.setBounds(170, 390, 80, 80);

        f1.setBackground(new java.awt.Color(249, 227, 133));
        f1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1MouseClicked(evt);
            }
        });

        label1.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Facility");

        javax.swing.GroupLayout f1Layout = new javax.swing.GroupLayout(f1);
        f1.setLayout(f1Layout);
        f1Layout.setHorizontalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        f1Layout.setVerticalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(f1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MapPanel.add(f1);
        f1.setBounds(70, 390, 90, 80);

        mapImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mallmap.png"))); // NOI18N
        MapPanel.add(mapImg);
        mapImg.setBounds(20, 33, 825, 606);

        RightBar.setBackground(new java.awt.Color(204, 204, 255));

        FacilityLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        FacilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FacilityLabel.setText("Select a Place");
        FacilityLabel.setToolTipText("");

        infoBtn.setBackground(new java.awt.Color(255, 102, 0));
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });

        infoText.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        infoText.setForeground(new java.awt.Color(255, 255, 255));
        infoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoText.setText("Place Information");

        javax.swing.GroupLayout infoBtnLayout = new javax.swing.GroupLayout(infoBtn);
        infoBtn.setLayout(infoBtnLayout);
        infoBtnLayout.setHorizontalGroup(
            infoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        infoBtnLayout.setVerticalGroup(
            infoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoText, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        dirBtn.setBackground(new java.awt.Color(0, 166, 0));
        dirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dirBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dirBtnMouseExited(evt);
            }
        });

        dirText.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        dirText.setForeground(new java.awt.Color(255, 255, 255));
        dirText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dirText.setText("Get Directions");

        javax.swing.GroupLayout dirBtnLayout = new javax.swing.GroupLayout(dirBtn);
        dirBtn.setLayout(dirBtnLayout);
        dirBtnLayout.setHorizontalGroup(
            dirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dirBtnLayout.setVerticalGroup(
            dirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirText, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        adPanel.setMaximumSize(new java.awt.Dimension(171, 80));
        adPanel.setMinimumSize(new java.awt.Dimension(171, 80));
        adPanel.setPreferredSize(new java.awt.Dimension(171, 80));

        adimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ad1.jpg"))); // NOI18N
        adimg.setPreferredSize(new java.awt.Dimension(171, 80));

        javax.swing.GroupLayout adPanelLayout = new javax.swing.GroupLayout(adPanel);
        adPanel.setLayout(adPanelLayout);
        adPanelLayout.setHorizontalGroup(
            adPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adPanelLayout.setVerticalGroup(
            adPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RightBarLayout = new javax.swing.GroupLayout(RightBar);
        RightBar.setLayout(RightBarLayout);
        RightBarLayout.setHorizontalGroup(
            RightBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FacilityLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RightBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RightBarLayout.setVerticalGroup(
            RightBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightBarLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(FacilityLabel)
                .addGap(64, 64, 64)
                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(adPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(MapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RightBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RightBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(MainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseEntered
        searchPanel.setBackground(new Color(123,173,244));
    }//GEN-LAST:event_searchPanelMouseEntered

    private void supportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportPanelMouseEntered
        supportPanel.setBackground(new Color(123,173,244));
    }//GEN-LAST:event_supportPanelMouseEntered

    private void searchPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseExited
        searchPanel.setBackground(new Color(104,134,197));
    }//GEN-LAST:event_searchPanelMouseExited

    private void supportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportPanelMouseExited
        supportPanel.setBackground(new Color(104,134,197));
    }//GEN-LAST:event_supportPanelMouseExited

    private void dirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirBtnMouseExited
        dirBtn.setBackground(new Color(0,166,0));
    }//GEN-LAST:event_dirBtnMouseExited

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
        infoBtn.setBackground(new Color(255,102,0));
    }//GEN-LAST:event_infoBtnMouseExited

    private void dirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirBtnMouseEntered
        dirBtn.setBackground(new Color(0,255,51));
    }//GEN-LAST:event_dirBtnMouseEntered

    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
        infoBtn.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_infoBtnMouseEntered

    private void f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseClicked
        FacilityLabel.setText(label1.getText());
    }//GEN-LAST:event_f1MouseClicked

    private void f3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseClicked
        FacilityLabel.setText(label3.getText());
    }//GEN-LAST:event_f3MouseClicked

    private void f4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4MouseClicked
        FacilityLabel.setText(label4.getText());
    }//GEN-LAST:event_f4MouseClicked

    private void f5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5MouseClicked
        FacilityLabel.setText(label5.getText());
    }//GEN-LAST:event_f5MouseClicked

    private void f6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f6MouseClicked
        FacilityLabel.setText(label6.getText());
    }//GEN-LAST:event_f6MouseClicked

    private void f7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f7MouseClicked
        FacilityLabel.setText(label7.getText());
    }//GEN-LAST:event_f7MouseClicked

    private void f8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f8MouseClicked
        FacilityLabel.setText(label8.getText());
    }//GEN-LAST:event_f8MouseClicked

    private void f9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f9MouseClicked
        FacilityLabel.setText(label9.getText());
    }//GEN-LAST:event_f9MouseClicked

    private void f10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f10MouseClicked
        FacilityLabel.setText(label10.getText());
    }//GEN-LAST:event_f10MouseClicked

    private void f11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f11MouseClicked
        FacilityLabel.setText(label11.getText());
    }//GEN-LAST:event_f11MouseClicked

    private void f12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f12MouseClicked
        FacilityLabel.setText(label12.getText());
    }//GEN-LAST:event_f12MouseClicked

    private void f13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f13MouseClicked
        FacilityLabel.setText(label13.getText());
    }//GEN-LAST:event_f13MouseClicked

    private void f14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f14MouseClicked
        FacilityLabel.setText(label14.getText());
    }//GEN-LAST:event_f14MouseClicked

    private void f15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f15MouseClicked
        FacilityLabel.setText(label15.getText());
    }//GEN-LAST:event_f15MouseClicked

    private void f16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f16MouseClicked
        FacilityLabel.setText(label16.getText());
    }//GEN-LAST:event_f16MouseClicked

    private void f17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f17MouseClicked
        FacilityLabel.setText(label17.getText());
    }//GEN-LAST:event_f17MouseClicked

    private void f18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f18MouseClicked
        FacilityLabel.setText(label18.getText());
    }//GEN-LAST:event_f18MouseClicked

    private void f2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseClicked
        FacilityLabel.setText(label2.getText());
    }//GEN-LAST:event_f2MouseClicked

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        String fn = FacilityLabel.getText();
        if(fn.equals("Select a Place"))
            JOptionPane.showMessageDialog(this, "Select a Place from the map First", "Error Message", ERROR_MESSAGE);
        else if(fn.equals("X"))
            JOptionPane.showMessageDialog(this, "Sorry! This place is currently unavailable", "Error Message", ERROR_MESSAGE);
        else
        {
            InfoDialog.setVisible(true);
            InfoDialog.setSize(400, 380);
            InfoDialog.setLocationRelativeTo(this);
                
            facilityInfoLabel.setText(fn);
            category.setText(mapm.getFacilityByName(fn).getCategory());
            phoneNum.setText(mapm.getFacilityByName(fn).getPhoneNo());
            workFrom.setText(String.valueOf(mapm.getFacilityByName(fn).getWorkingHours()[0]));
            workTo.setText(String.valueOf(mapm.getFacilityByName(fn).getWorkingHours()[1]));
            description.setText("<html><p>" + mapm.getFacilityByName(fn).getDescription() + "</p></html>");
        }
    }//GEN-LAST:event_infoBtnMouseClicked

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        InfoDialog.dispose();
    }//GEN-LAST:event_okBtnMouseClicked

    private void supportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportPanelMouseClicked
        //JOptionPane.showMessageDialog(this, "Sorry! Customer Service is busy now. Please try again later..", "Error Message", INFORMATION_MESSAGE);
        SupportDialog.setVisible(true);
        SupportDialog.setSize(400, 350);
        SupportDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_supportPanelMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        SupportDialog.dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void sendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseClicked
        String desc = (String)inqDescription.getText();
        String type = (String)inqTypeBox.getSelectedItem();
        
        if (type.equals(null) || type.equals(""))
            JOptionPane.showMessageDialog(this, "Please, Choose the Type of the Inquiry!", "Invalid Input", ERROR_MESSAGE);
        else if (desc.equals("Write your Inquiry here") || desc.equals(""))
            JOptionPane.showMessageDialog(this, "Please, Enter the Inquiry!", "Invalid Input", ERROR_MESSAGE);
        else
        {
            mapm.sendInquiry(type, desc);
            JOptionPane.showMessageDialog(this, "Your Inquiry is sent. Thank you for Reaching us!", "Confirmation", INFORMATION_MESSAGE);
            SupportDialog.dispose();
        }
    }//GEN-LAST:event_sendBtnMouseClicked

    private void callBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callBtnMouseClicked
        JOptionPane.showMessageDialog(this, "Please wait, Connecting to the Support team..", "Confirmation", INFORMATION_MESSAGE);
        mapm.sendInquiry("Call", "");
    }//GEN-LAST:event_callBtnMouseClicked

    private void dirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirBtnMouseClicked
        String fn = FacilityLabel.getText();
        if(fn.equals("Select a Place"))
            JOptionPane.showMessageDialog(this, "Select a Place from the map First", "Error Message", ERROR_MESSAGE);
        else if(fn.equals("X"))
            JOptionPane.showMessageDialog(this, "Sorry! This place is currently unavailable", "Error Message", ERROR_MESSAGE);
        else
        {
            Graphics g = this.getGraphics();
            paint(g);
            g.setColor(Color.red);
            int[][] d = mapm.getDirection(fn);
            for(int i = 1; i <= d[0][0]; i++)
                g.drawLine(d[i][0], d[i][1], d[i+1][0], d[i+1][1]);
        }       
    }//GEN-LAST:event_dirBtnMouseClicked
    @Override
    public void paint(Graphics g){
        super.paint(g);
    }
        
    
    private void AllFacilityMouseEntered()
    {
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f1);
            }
        });
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f2);
            }
        });
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f3);
            }
        });
        f4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f4);
            }
        });
        f5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f5);
            }
        });
        f6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f6);
            }
        });
        f7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f7);
            }
        });
        f8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f8);
            }
        });
        f9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f9);
            }
        });
        f10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f10);
            }
        });
        f11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f11);
                label11.setVisible(true);
            }
        });
        f12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f12);
            }
        });
        f13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f13);
            }
        });
        f14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f14);
            }
        });
        f15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f15);
            }
        });
        f16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f16);
            }
        });
        f17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f17);
            }
        });
        f18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facilityMouseEntered(evt, f18);
            }
        });
        
    } 
    private void facilityMouseEntered(java.awt.event.MouseEvent evt, javax.swing.JPanel f) {                                 
        f.setBackground(new Color(247,208,17));
        if(f.equals(f11) || f.equals(f12))
        {
            f.setOpaque(true);
        }
    } 
    
    private void AllFacilityMouseExited()
    {
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f1);
            }
        });
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f2);
            }
        });
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f3);
            }
        });
        f4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f4);
            }
        });
        f5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f5);
            }
        });
        f6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f6);
            }
        });
        f7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f7);
            }
        });
        f8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f8);
            }
        });
        f9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f9);
            }
        });
        f10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f10);
            }
        });
        f11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f11);
                label11.setVisible(false);
            }
        });
        f12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f12);
            }
        });
        f13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f13);
            }
        });
        f14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f14);
            }
        });
        f15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f15);
            }
        });
        f16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f16);
            }
        });
        f17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f17);
            }
        });
        f18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facilityMouseExited(evt, f18);
            }
        });
        
    } 
    private void facilityMouseExited(java.awt.event.MouseEvent evt, javax.swing.JPanel f) {                                 
        f.setBackground(new Color(249,227,133));
        if(f.equals(f11) || f.equals(f12))
        {
            f.setOpaque(false);
        }
    } 
    
    private void mapFacilityView()
    {       
        label1.setText(mapm.getFacilityName("F1"));
        label2.setText(mapm.getFacilityName("F2"));
        label3.setText(mapm.getFacilityName("F3"));
        label4.setText(mapm.getFacilityName("F4"));
        label5.setText(mapm.getFacilityName("F5"));
        label6.setText(mapm.getFacilityName("F6"));
        label7.setText(mapm.getFacilityName("F7"));
        label8.setText(mapm.getFacilityName("F8"));
        label9.setText(mapm.getFacilityName("F9"));
        label10.setText(mapm.getFacilityName("F10"));
        label11.setText(mapm.getFacilityName("F11"));
        label12.setText(mapm.getFacilityName("F12"));
        label13.setText(mapm.getFacilityName("F13"));
        label14.setText(mapm.getFacilityName("F14"));
        label15.setText(mapm.getFacilityName("F15"));
        label16.setText(mapm.getFacilityName("F16"));
        label17.setText(mapm.getFacilityName("F17"));
        label18.setText(mapm.getFacilityName("F18"));
    }


    
    public static void main(String args[]) 
    {
        //<editor-fold defaultstate="collapsed" desc="Windows Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FacilityLabel;
    private javax.swing.JDialog InfoDialog;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JPanel InqPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MapLogo;
    private javax.swing.JLabel MapLogo1;
    private javax.swing.JLabel MapLogo2;
    private javax.swing.JPanel MapPanel;
    private javax.swing.JPanel RightBar;
    private javax.swing.JPanel SideBar;
    private javax.swing.JDialog SupportDialog;
    private javax.swing.JPanel adPanel;
    private javax.swing.JLabel adimg;
    private javax.swing.JButton callBtn;
    private javax.swing.JLabel callicon;
    private javax.swing.JLabel calltext;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel category;
    private javax.swing.JLabel description;
    private javax.swing.JPanel dirBtn;
    private javax.swing.JLabel dirText;
    private javax.swing.JPanel f1;
    private javax.swing.JPanel f10;
    private javax.swing.JPanel f11;
    private javax.swing.JPanel f12;
    private javax.swing.JPanel f13;
    private javax.swing.JPanel f14;
    private javax.swing.JPanel f15;
    private javax.swing.JPanel f16;
    private javax.swing.JPanel f17;
    private javax.swing.JPanel f18;
    private javax.swing.JPanel f2;
    private javax.swing.JPanel f3;
    private javax.swing.JPanel f4;
    private javax.swing.JPanel f5;
    private javax.swing.JPanel f6;
    private javax.swing.JPanel f7;
    private javax.swing.JPanel f8;
    private javax.swing.JPanel f9;
    private javax.swing.JLabel facilityInfoLabel;
    private javax.swing.JPanel infoBtn;
    private javax.swing.JLabel infoText;
    private javax.swing.JTextPane inqDescription;
    private javax.swing.JLabel inqLabel;
    private javax.swing.JComboBox<String> inqTypeBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel mapImg;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel phoneNum;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel searchicon;
    private javax.swing.JButton sendBtn;
    private javax.swing.JPanel supportPanel;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel workFrom;
    private javax.swing.JLabel workTo;
    // End of variables declaration//GEN-END:variables
}
